{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  labels:
    app: {{ $.Release.Name }}-{{ $name }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}-{{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}
